Rent_Flat_Core/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Rent_Flat_Core.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult MainMenu()
        {
            return PartialView();
        }

        //----------------------------------- MENÚ DEL BACK
        public IActionResult BackMainMenu()
        {
            return PartialView();
        }
    }
}

Rent_Flat_Core/Controllers/ValidacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Rent_Flat_Core.Models;
using Rent_Flat_Core.Repositories;
using Rent_Flat_Core.Services;

namespace Rent_Flat_Core.Controllers
{
    public class ValidacionController : Controller
    {
        RepositoryApiRent repo;
        public ValidacionController()
        {
            this.repo = new RepositoryApiRent();


        }

        //------------------------
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(String usuario, String password)
        {
             if(string.IsNullOrEmpty(usuario) || string.IsNullOrEmpty(password))
            {
                ViewBag.Mensaje = "Usuario/Password incorrectos";
                return View();
            }
            EncodingService encoding = new EncodingService();
            //BUSCAMOS EL TOKEN PARA COMPROBAR LAS CREDENCIALES
            //DEL EMPLEADO
            String token = await this.repo.GetToken(usuario, encoding.SHA256(password));
            //SI EL TOKEN ES NULL, NO TIENE CREDENCIALES
            if (token != null)
            {
                HttpContext.Session.SetString("TOKEN", token);//esta es la linea importante de acceso con la api
                //SI TENEMOS TOKEN, TENEMOS EMPLEADO
                //POR LO QUE PODEMOS RECUPERARLO DEL METODO PERFILEMPLEADO
                Usuarios empleado = await
                    this.repo.PerfilEmpleado(token);
                //CREAMOS AL USUARIO PARA EL ENTORNO MVC DE CORE
                ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                //ALMACENAMOS EL ID DE EMPLEADO
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier
                    , empleado.Login));
                identity.AddClaim(new Claim(ClaimTypes.Name, empleado.Apellido+", "+empleado.Nombre));
                //GUARDAMOS TAMBIEN EL ROLE DEL EMPLEADO
                identity.AddClaim(new Claim(ClaimTypes.Role, empleado.Perfil));
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme, principal
                    , new AuthenticationProperties
                    {
                        IsPersistent = true
                    ,//DEBERIAMOS DAR EL MISMO TIEMPO DE SESSION QUE TOKEN
                        ExpiresUtc = DateTime.Now.AddMinutes(60)
                    });
                //UNA VEZ QUE TENEMOS A NUESTRO EMPLEADO ALMACENADO
                //DEBEMOS ALMACENAR EL TOKEN EN SESSION PARA PODER REUTILIZARLO
                //EN OTROS METODOS DE LA APP

                //REDIRECCIONAMOS A UNA PAGINA DE INICIO PROTEGIDA
                return RedirectToAction("Index", "BackHome");
            }
            else
            {
                ViewBag.Mensaje = "Usuario/Password incorrectos";
                return View();
            }
        }


        public async Task<IActionResult> CerrarSesion()
        {
            await HttpContext.SignOutAsync
            (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

    }
}

Rent_Flat_Core/Views/Shared/PlantillaBack.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Required meta tags-->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <environment include="Development">



        <link href="~/Back/css/font-face.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/wow/animate.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/slick/slick.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/select2/select2.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">
        <link href="~/Back/css/theme.css" rel="stylesheet" media="all">
    </environment>
    <environment include="Production">



        <link href="~/Back/css/font-face.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/wow/animate.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/slick/slick.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/select2/select2.min.css" rel="stylesheet" media="all">
        <link href="~/Back/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">
        <link href="~/Back/css/theme.css" rel="stylesheet" media="all">
    </environment>
    @RenderSection("styles", false)

</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner" style="background-color:blue;">
                        <a class="logo" href="@Url.Action("Index", "Home")">
                            <img src="~/Front/images/logo.png" alt="">
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">

                        @*@{ Html.RenderAction("BackMainMenu", "Menu");}*@

                        <partial name="~/Views/Menu/BackMainMenu.cshtml" />
                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->
        <!-- MENU SIDEBAR-->

        <aside class="menu-sidebar d-none d-lg-block">
            <div class="welcome2 p-t-40 p-b-55" style="background-color:#393939;">
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/Front/images/logo.png" alt="">
                </a>
            </div>

            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        @*@{
                            Html.RenderAction("BackMainMenu", "Menu");
                        }*@
                        <partial name="~/Views/Menu/BackMainMenu.cshtml" />
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->

        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="welcome2 p-t-40 p-b-55">
                @*MOSTRAR EL NOMBRE DEL DIRECTOR QUE TIENE LA SESSION ABIERTA*@
                @if (Context.User.Identity.IsAuthenticated)
                {
                    <h1 class="title-6">
                        Bienvenido Sr/Sra @Context.User.Identity.Name

                    </h1>
                    @Html.ActionLink("Cerrar sesión", "CerrarSesion", "Validacion")
                }


            </header>
            <!-- HEADER DESKTOP-->

            <div class="main-content">
                <div class="section__content section__content--p30">
                    @RenderBody()
                </div>
                
             
            </div>
        </div>

        <environment include="Development">
            <script src="~/Back/vendor/jquery-3.2.1.min.js"></script>
            <!-- Bootstrap JS-->
            <script src="~/Back/vendor/bootstrap-4.1/popper.min.js"></script>
            <script src="~/Back/vendor/bootstrap-4.1/bootstrap.min.js"></script>
            <!-- Vendor JS       -->
            <script src="~/Back/vendor/slick/slick.min.js">
            </script>
            <script src="~/Back/vendor/wow/wow.min.js"></script>
            <script src="~/Back/vendor/animsition/animsition.min.js"></script>
            <script src="~/Back/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
            </script>
            <script src="~/Back/vendor/counter-up/jquery.waypoints.min.js"></script>
            <script src="~/Back/vendor/counter-up/jquery.counterup.min.js">
            </script>
            <script src="~/Back/vendor/circle-progress/circle-progress.min.js"></script>
            <script src="~/Back/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
            <script src="~/Back/vendor/chartjs/Chart.bundle.min.js"></script>
            <script src="~/Back/vendor/select2/select2.min.js">
            </script>




            <!-- Main JS-->
            <script src="~/Back/js/main.js"></script>
        </environment>
        <environment include="Production">
            <script src="~/Back/vendor/jquery-3.2.1.min.js"></script>
            <!-- Bootstrap JS-->
            <script src="~/Back/vendor/bootstrap-4.1/popper.min.js"></script>
            <script src="~/Back/vendor/bootstrap-4.1/bootstrap.min.js"></script>
            <!-- Vendor JS       -->
            <script src="~/Back/vendor/slick/slick.min.js">
            </script>
            <script src="~/Back/vendor/wow/wow.min.js"></script>
            <script src="~/Back/vendor/animsition/animsition.min.js"></script>
            <script src="~/Back/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
            </script>
            <script src="~/Back/vendor/counter-up/jquery.waypoints.min.js"></script>
            <script src="~/Back/vendor/counter-up/jquery.counterup.min.js">
            </script>
            <script src="~/Back/vendor/circle-progress/circle-progress.min.js"></script>
            <script src="~/Back/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
            <script src="~/Back/vendor/chartjs/Chart.bundle.min.js"></script>
            <script src="~/Back/vendor/select2/select2.min.js">
            </script>




            <!-- Main JS-->
            <script src="~/Back/js/main.js"></script>
        </environment>
        @RenderSection("scripts", false)

    </div>
</body>
</html>

Rent_Flat_Core/Views/Shared/PlantillaFront.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <title>RENT A FLAT</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Bluesky template project">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <environment include="Development">

        <link href="~/Front/styles/bootstrap4/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Front/plugins/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="~/Front/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
        <link rel="stylesheet" type="text/css" href="~/Front/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
        <link rel="stylesheet" type="text/css" href="~/Front/plugins/OwlCarousel2-2.2.1/animate.css">
        <link rel="stylesheet" type="text/css" href="~/Front/styles/main_styles.css">
        <link rel="stylesheet" type="text/css" href="~/Front/styles/responsive.css">
    </environment>
    <environment include="Production">

        <link href="~/Front/styles/bootstrap4/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Front/plugins/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="~/Front/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
        <link rel="stylesheet" type="text/css" href="~/Front/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
        <link rel="stylesheet" type="text/css" href="~/Front/plugins/OwlCarousel2-2.2.1/animate.css">
        <link rel="stylesheet" type="text/css" href="~/Front/styles/main_styles.css">
        <link rel="stylesheet" type="text/css" href="~/Front/styles/responsive.css">
    </environment>
    @RenderSection("styles", false)
</head>

<body>
    @*HEAD******************************************************************************************BEGIN NAV*@
    <div class="super_container">
        <header class="header">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="header_content d-flex flex-row align-items-center justify-content-start">
                            <div class="logo">
                                <img src="~/Front/images/logo.png" alt="">
                            </div>
                            <nav class="main_nav">

                                <partial name="~/Views/Menu/MainMenu.cshtml" />



                            </nav>

                            <div class="phone_num ml-auto">
                                <div class="phone_num_inner">
                                    <img src="~/Front/images/phone.png" alt=""><span>91 548 99 78</span>

                                </div>
                            </div>
                            <div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        @*t*************************************************************************************************************FIN NAV*@


        <!-- ***********************************************************************************************************MENU<500PX -->

        <div class="menu trans_500">
            <div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
                <div class="menu_close_container"><div class="menu_close"></div></div>
                <div class="logo menu_logo">
                    <a href="#">
                        <div class="logo_container d-flex flex-row align-items-start justify-content-start">
                            <div class="logo_image"><div><img src="~/Front/images/logo.png" alt=""></div></div>
                        </div>
                    </a>
                </div>

                <partial name="~/Views/Menu/MainMenu.cshtml" />

            </div>
            <div class="menu_phone"><span>call us: </span>91 548 99 78</div>
        </div>
        <!-- *********************************************************************************************************FIN MENU<500PX -->









        @RenderBody()


    </div>


    <!-- Footer -->

    <footer class="footer">
        <div class="footer_main">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="footer_logo"><a href="#"><img src="~/Front/images/logo_large.png" alt=""></a></div>
                    </div>
                    <div class="col-lg-9 d-flex flex-column align-items-start justify-content-end">
                        <div class="footer_title">
                            Rent a flat
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3 footer_col">
                        <div class="footer_about">
                            <div class="footer_about_text">Encuentra la casa de tus sueños en la playa</div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </footer>

    <environment include="Development">
        <script src="~/Front/js/jquery-3.2.1.min.js"></script>
        <script src="~/Front/styles/bootstrap4/popper.js"></script>
        <script src="~/Front/styles/bootstrap4/bootstrap.min.js"></script>
        <script src="~/Front/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
        <script src="~/Front/plugins/easing/easing.js"></script>
        <script src="~/Front/plugins/parallax-js-master/parallax.min.js"></script>
        <script src="~/Front/js/custom.js"></script>
    </environment>
    <environment include="Production">
        <script src="~/Front/js/jquery-3.2.1.min.js"></script>
        <script src="~/Front/styles/bootstrap4/popper.js"></script>
        <script src="~/Front/styles/bootstrap4/bootstrap.min.js"></script>
        <script src="~/Front/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
        <script src="~/Front/plugins/easing/easing.js"></script>
        <script src="~/Front/plugins/parallax-js-master/parallax.min.js"></script>
        <script src="~/Front/js/custom.js"></script>
    </environment>
    @RenderSection("scripts", false)



</body>

</html>

Rent_Flat_Core/Views/Shared/PlantillaLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">
    <!-- Title Page-->
    <title>Login</title>
    <!-- Fontfaces CSS-->
    <link href="~/Back/css/font-face.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all" />

    <!-- Bootstrap CSS-->
    <link href="~/Content/Back/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all" />

    <!-- Vendor CSS-->
    <link href="~/Back/vendor/animsition/animsition.min.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/wow/animate.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/slick/slick.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/select2/select2.min.css" rel="stylesheet" media="all" />
    <link href="~/Back/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all" />
    <!-- Main CSS-->
    <link href="~/Back/css/theme.css" rel="stylesheet" media="all" />

</head>
<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo" style="background-color:blue;">
                            <a href="@Url.Action("Index","Home")">
                                <img src="~/Front/images/logo.png" alt="">
                                @*<img src="images/icon/logo.png" alt="CoolAdmin">*@
                            </a>
                        </div>

                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- Jquery JS-->
    <script src="~/Back/vendor/jquery-3.2.1.min.js"></script>

    <!-- Bootstrap JS-->
    <script src="~/Back/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Back/vendor/bootstrap-4.1/bootstrap.min.js"></script>

    <!-- Vendor JS       -->
    <script src="~/Back/vendor/slick/slick.min.js"></script>
    <script src="~/Back/vendor/wow/wow.min.js"></script>
    <script src="~/Back/vendor/animsition/animsition.min.js"></script>
    <script src="~/Back/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <script src="~/Back/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Back/vendor/counter-up/jquery.counterup.min.js"></script>
    <script src="~/Back/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Back/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/Back/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Back/vendor/select2/select2.min.js"></script>

    <!-- Main JS-->
    <script src="~/Back/js/main.js"></script>
</body>
</html>
<!-- end document-->